INSERT INTO PRE_NCR.TB_STAGE10_3
WITH 
SALES_DISCOUNTS_C_S_R AS (
SELECT DISTINCT 
	t1.COMPANY_CODE,  
	CASE 
		WHEN t1.COMPANY_CODE IN ('1020','3000','6000') THEN 'North East'
		WHEN t1.COMPANY_CODE IN ('5010','1030') THEN 'West'
		WHEN t1.COMPANY_CODE IN ('1010') THEN 'East'
		WHEN t1.COMPANY_CODE IN ('1040') THEN 'Central'
		ELSE 'Others'
	END AS REGION,
		t1.STATE_CODE AS SP_STATE,
		t1.RATE_CODE AS  RATECODE_DEPOTCODE,
		t1.VALID_FROM, 
		t1.VALID_TO,
		t1.CASH_DISCOUNT_CD, 
		t1.QUARTERLY_DISCOUNT_QD ,
		t1.SUB_DEALER_DISCOUNT ,
		t1.NEW_DISCOUNT_1, 
		t1.NEW_DISCOUNT_2,
		t1.NEW_DISCOUNT_3,
		t1.NEW_DISCOUNT_4, 
		t1.NEW_DISCOUNT_5,
		t1.NEW_DISCOUNT_6,
		t1.NEW_DISCOUNT_7,
		t1.NEW_DISCOUNT_8, 
		t1.MONTHS,
		t1.YEARS,
		t1.LASF 
FROM MAN_UPLOAD.SALES_DISCOUNTS_C_S_R t1),
DISCOUNT_NEW_2 AS (
SELECT 
	t2.BILLINGDOCUMENT, 
	t2.BILLINGDATE,
	t3.VALID_FROM AS DATE_DIST_FROM,
	MAX(t3.CASH_DISCOUNT_CD) AS  CASH_DISCOUNT_CD_NEW ,
	MAX(t3.QUARTERLY_DISCOUNT_QD) AS QUARTERLY_DISCOUNT_QD_NEW ,
	MAX(t3.SUB_DEALER_DISCOUNT) AS SUB_DEALER_DISCOUNT_NEW,
	MAX(t3.NEW_DISCOUNT_1) AS NEW_DISCOUNT_1_NEW,
	MAX(t3.NEW_DISCOUNT_2) AS NEW_DISCOUNT_2_NEW ,
	MAX(t3.NEW_DISCOUNT_3) AS NEW_DISCOUNT_3_NEW,
	MAX(t3.NEW_DISCOUNT_4) AS NEW_DISCOUNT_4_NEW,
	MAX(t3.NEW_DISCOUNT_5) AS NEW_DISCOUNT_5_NEW,
	MAX(t3.NEW_DISCOUNT_6) AS NEW_DISCOUNT_6_NEW,
	MAX(t3.NEW_DISCOUNT_7) AS NEW_DISCOUNT_7_NEW,
	MAX(t3.NEW_DISCOUNT_8) AS NEW_DISCOUNT_8_NEW,
	MAX(t3.LASF) AS LASF_NEW
FROM EDWDM.TB_SALES_Z_DISP t2
LEFT JOIN SALES_DISCOUNTS_C_S_R t3 ON t2.SALES_ORGANISATION=t3.COMPANY_CODE AND RIGHT(CONCAT('0',t3.SP_STATE),2)=t2.SHIP_TO_STATE 
AND t2.GEOGDISTRICTCODE=t3.RATECODE_DEPOTCODE AND t2.REGION=t3.REGION AND (CAST(t2.BILLINGDATE AS DATE) BETWEEN t3.VALID_FROM AND t3.VALID_TO) 
WHERE t2.BILLINGDATE>='20220401'
GROUP BY t2.BILLINGDOCUMENT, t2.BILLINGDATE, t3.VALID_FROM
UNION
SELECT 
	t4.BILLINGDOCUMENT,
	t4.BILLINGDATE,
	t5.VALID_FROM AS DATE_DIST_FROM,
	MAX(t5.CASH_DISCOUNT_CD) AS  CASH_DISCOUNT_CD_NEW,
	MAX(t5.QUARTERLY_DISCOUNT_QD) AS QUARTERLY_DISCOUNT_QD_NEW ,
	MAX(t5.SUB_DEALER_DISCOUNT) AS SUB_DEALER_DISCOUNT_NEW,
	MAX(t5.NEW_DISCOUNT_1) AS NEW_DISCOUNT_1_NEW,
	MAX(t5.NEW_DISCOUNT_2) AS NEW_DISCOUNT_2_NEW,
	MAX(t5.NEW_DISCOUNT_3) AS NEW_DISCOUNT_3_NEW,
	MAX(t5.NEW_DISCOUNT_4) AS NEW_DISCOUNT_4_NEW,
	MAX(t5.NEW_DISCOUNT_5) AS NEW_DISCOUNT_5_NEW,
	MAX(t5.NEW_DISCOUNT_6) AS NEW_DISCOUNT_6_NEW,
	MAX(t5.NEW_DISCOUNT_7) AS NEW_DISCOUNT_7_NEW,
	MAX(t5.NEW_DISCOUNT_8) AS NEW_DISCOUNT_8_NEW,
	MAX(t5.LASF) AS LASF_NEW
FROM EDWDM.TB_SALES_Z_DISP t4
LEFT JOIN SALES_DISCOUNTS_C_S_R t5 ON RIGHT(CONCAT('0',t5.SP_STATE),2)=t4.SHIP_TO_STATE 
AND t4.GEOGDISTRICTCODE=t5.RATECODE_DEPOTCODE AND t4.REGION=t5.REGION AND (CAST(t4.BILLINGDATE AS DATE) BETWEEN t5.VALID_FROM AND t5.VALID_TO) 
WHERE t4.BILLINGDATE<'20220401'
GROUP BY t4.BILLINGDOCUMENT, t4.BILLINGDATE, t5.VALID_FROM ) 

SELECT DISTINCT 
	a.BILLINGDOCUMENT,
	a.BILLINGDATE,
	b.RATE AS DIRECTDISPATCHDISCOINT_INV_CUS,
	c.MOVING_AVERAGE_PRICE_VERPR,
	d.RATE AS DIRECTDISPATCHDISCOINT_SO_MP_CUS,
	e.DAP_ID,
	e.BP_TYPE,
	f.MATERIAL_GROUP,
	f.MATERIAL_BRAND,
	f.BAG_TYPE,
	f.BAG_LOOSE,
	f.MATERIAL_SUBTYPE AS QUALITY,
	CASE 
		WHEN f.MATERIAL_SUBTYPE LIKE '%DSP' THEN 'DSP'
		WHEN f.MATERIAL_SUBTYPE LIKE  '%OPC' THEN 'DIP/OPC'
		WHEN f.MATERIAL_SUBTYPE LIKE 'I-%' THEN 'DIP/OPC'
		WHEN f.MATERIAL_SUBTYPE LIKE 'V-%' THEN 'Vaj'
		WHEN f.MATERIAL_SUBTYPE LIKE 'K-*' THEN 'Kon'
		ELSE 'Dalmia'
	END AS NET_PRICE_BRAND,
	g.PRICE_DISCOUNT AS RATE_INCO_PLANT_PRODUCT,
	h.PRICE_DISCOUNT_RATE AS PD,
	i.DISTANCE,
	j.DISCOUNT_RATE,
	k.QUATERLY_DISCOUNT_QD_SOUTH,
	l.PD_COUNTY_WISE,
	m.CASH_DISCOUNT_CD_NEW, 
	m.QUARTERLY_DISCOUNT_QD_NEW,
	m.SUB_DEALER_DISCOUNT_NEW,
	m.NEW_DISCOUNT_1_NEW, 
	m.NEW_DISCOUNT_2_NEW,
	m.NEW_DISCOUNT_3_NEW,
	m.NEW_DISCOUNT_4_NEW, 
	m.NEW_DISCOUNT_5_NEW,
	m.NEW_DISCOUNT_6_NEW,
	m.NEW_DISCOUNT_7_NEW,
	m.NEW_DISCOUNT_8_NEW,
	m.LASF_NEW,
	m.DATE_DIST_FROM,
	n.PRICE_DISCOUNT_RATE AS PD_STATE_INCO_SALESDIST_PRODUCT,
	w.PRICE_DISCOUNT_RATE AS PD_COUNTY_WISE_U,
	a.DIRECT_DEPOT_INCL_E2E,
	a.BUSINESS_AREA,
	a.PROFIT_CENTRE
FROM EDWDM.TB_SALES_Z_DISP a 

LEFT JOIN MAN_UPLOAD.DIRECTDISPATCHDISCOINT_INV_CUS b ON a.BILLINGDOCUMENT=b.INVOICENO AND CAST(a.BILLINGDATE AS DATE)=b.INVOICE_DATE

LEFT JOIN EDWDM.TB_PACKING c ON a.BILLINGDOCUMENT=c.BILLINGDOCUMENT AND a.BILLINGDATE=c.BILLINGDATE

LEFT JOIN ( SELECT SALES_ORDER_NO, MOTHER_PLANT, MAX(RATE) AS RATE FROM MAN_UPLOAD.DIRECTDISPATCHDISCOINT_SO_MP_CUS GROUP BY SALES_ORDER_NO, MOTHER_PLANT 
) d ON a.SONUMBER=d.SALES_ORDER_NO AND a.MANUFACTURING_PLANT=d.MOTHER_PLANT

LEFT JOIN EDWDM.TB_CUST_MASTER_INFO e ON e.BUSINESS_PARTNER_CODE=a.SHIPTOPARTYCODE

LEFT JOIN EDWDM.TB_MATERIAL_INFO f ON f.MATERIAL_CODE=a.MATERIALNUMBER

LEFT JOIN ( SELECT COMPANY_CODE, STATE_CODE, INCO_TERM, PLANT_CODE, MATERIAL_CODE, VALID_FROM, VALID_TO, MAX(PRICE_DISCOUNT) AS PRICE_DISCOUNT 
FROM MAN_UPLOAD.SALES_PRICE_DISCOUNT_C_S_I_P_M GROUP BY COMPANY_CODE, STATE_CODE, INCO_TERM, PLANT_CODE, MATERIAL_CODE, VALID_FROM, VALID_TO 
) g ON a.SHIP_TO_STATE=RIGHT(CONCAT('0',g.STATE_CODE),2) AND a.SALES_ORGANISATION=g.COMPANY_CODE AND g.INCO_TERM=a.INCOTERMS1
AND a.PLANTCODE=g.PLANT_CODE AND a.MATERIALNUMBER=g.MATERIAL_CODE AND (CAST(a.BILLINGDATE AS DATE) BETWEEN g.VALID_FROM AND g.VALID_TO)

LEFT JOIN ( SELECT COMPANY_CODE, SOLD_TO_PARTY_CODE, VALID_FROM, VALID_TO, MAX(PRICE_DISCOUNT_RATE) AS PRICE_DISCOUNT_RATE
FROM MAN_UPLOAD.SALES_PRICE_DISCOUNT_C_SOLD GROUP BY COMPANY_CODE, SOLD_TO_PARTY_CODE, VALID_FROM, VALID_TO
) h ON a.SALES_ORGANISATION=h.COMPANY_CODE AND a.SOLDTOPARTYCODE=RIGHT(CONCAT('0000000000',h.SOLD_TO_PARTY_CODE),10)
AND (CAST(a.BILLINGDATE AS DATE) BETWEEN h.VALID_FROM AND h.VALID_TO)

LEFT JOIN ( SELECT FINAL_SOURCE, FINAL_DESTINATION, MODE_OF_SUPPLY, MAX(DISTANCE) AS DISTANCE 
FROM EDWDM.TB_PLANT_DEPOT_DISTANCE GROUP BY FINAL_SOURCE, FINAL_DESTINATION, MODE_OF_SUPPLY 
) i ON a.MANUFACTURING_PLANT=i.FINAL_SOURCE AND a.PLANTCODE=i.FINAL_DESTINATION AND a.MODEOFTRANSPORT=i.MODE_OF_SUPPLY

LEFT JOIN ( SELECT t6.COMPANY_CODE, t6.SOLD_TO_PARTY AS SOLD_TO_PARTY_CODE, MAX(t6.DISCOUNT_RATE) AS DISCOUNT_RATE, t6.VALID_FROM, t6.VALID_TO, t7.SHIPTOPARTYCODE
FROM MAN_UPLOAD.SALES_DICOUNTS_C_SOLD t6 
LEFT JOIN EDWDM.TB_SALES_Z_DISP t7 ON RIGHT(CONCAT('0000000000',t7.SOLDTOPARTYCODE),10)=t6.SOLD_TO_PARTY 
GROUP BY t6.COMPANY_CODE, t6.SOLD_TO_PARTY, t6.VALID_FROM, t6.VALID_TO, t7.SHIPTOPARTYCODE 
) j ON j.COMPANY_CODE=a.SALES_ORGANISATION AND a.SOLDTOPARTYCODE=j.SOLD_TO_PARTY_CODE AND j.SHIPTOPARTYCODE=a.SHIPTOPARTYCODE 
AND (CAST(a.BILLINGDATE AS DATE) BETWEEN j.VALID_FROM AND j.VALID_TO)

LEFT JOIN ( SELECT DISTRIBUTION_CHANNEL AS DCHL, STATE_CODE AS SP_STATE, RATE_CODE AS RATECODE_DEPOT_CODE, VALID_FROM AS DATE_DIST_FROM, VALID_TO AS DATE_DIST_TO,
MAX(NEW_DISCOUNT_4+QUARTERLY_DISCOUNT_QD) AS QUATERLY_DISCOUNT_QD_SOUTH
FROM MAN_UPLOAD.SALES_DISCOUNT_C_DBC_S_R GROUP BY DISTRIBUTION_CHANNEL, STATE_CODE, RATE_CODE, VALID_FROM, VALID_TO  
) k ON a.DISTRIBUTIONCHANNEL=RIGHT(CONCAT('0',k.DCHL),2) AND a.GEOGDISTRICTCODE=k.RATECODE_DEPOT_CODE AND a.SHIP_TO_STATE=RIGHT(CONCAT('0',k.SP_STATE),2)  
AND (CAST(a.BILLINGDATE AS DATE) BETWEEN k.DATE_DIST_FROM AND k.DATE_DIST_TO)

LEFT JOIN ( SELECT COMPANY_CODE, STATE_CODE, SH_COUNTY_CODE, MATERIAL_CODE, VALID_FROM, VALID_TO, MAX(PRICE_DISCOUNT_RATE) AS PD_COUNTY_WISE 
FROM MAN_UPLOAD.SALES_PRICE_DISCOUNT_C_S_CO_M GROUP BY COMPANY_CODE, STATE_CODE, SH_COUNTY_CODE, MATERIAL_CODE, VALID_FROM, VALID_TO 
) l ON a.SALES_ORGANISATION=l.COMPANY_CODE AND RIGHT(CONCAT('0',l.STATE_CODE),2)=a.SHIP_TO_STATE
AND a.SHIP_TO_COUNTYCODE=RIGHT(CONCAT('000',SH_COUNTY_CODE),3) AND a.MATERIALNUMBER=l.MATERIAL_CODE
AND (CAST(a.BILLINGDATE AS DATE) BETWEEN l.VALID_FROM AND l.VALID_TO) 

LEFT JOIN DISCOUNT_NEW_2 m ON a.BILLINGDOCUMENT=m.BILLINGDOCUMENT AND a.BILLINGDATE=m.BILLINGDATE

LEFT JOIN ( SELECT COMPANY_CODE, STATE_CODE, INCO_TERM, SALES_DISTRICT, MATERIAL_CODE, YEARS, MONTHS, MAX(PRICE_DISCOUNT_RATE) AS PRICE_DISCOUNT_RATE 
FROM MAN_UPLOAD.SALES_PRICE_DISCOUNT_C_S_I_SD_M GROUP BY COMPANY_CODE, STATE_CODE, INCO_TERM, SALES_DISTRICT, MATERIAL_CODE, YEARS, MONTHS 
) n ON a.SALES_ORGANISATION=n.COMPANY_CODE AND a.SHIP_TO_STATE=RIGHT(CONCAT('0',n.STATE_CODE),2) AND a.GEOGDISTRICTCODE=n.SALES_DISTRICT AND a.INCOTERMS1=n.INCO_TERM 
AND a.MATERIALNUMBER=n.MATERIAL_CODE AND EXTRACT(YEAR FROM CAST(a.BILLINGDATE AS DATE))=n.YEARS AND TO_CHAR(CAST(a.BILLINGDATE AS DATE), 'MONTH')=UPPER(n.MONTHS)

LEFT JOIN ( SELECT DISTINCT UNLOADING_POINT_REGIO, UNLOADING_POINT_COUNTY_CO, MATERIAL_CODE, MAX(PRICE_DISCOUNT_RATE) AS PRICE_DISCOUNT_RATE ,VALID_FROM, VALID_TO 
FROM MAN_UPLOAD.SALES_PRICE_DISCOUNT_C_S_CO_M_U GROUP BY UNLOADING_POINT_REGIO, UNLOADING_POINT_COUNTY_CO, MATERIAL_CODE, VALID_FROM, VALID_TO 
) w ON RIGHT(CONCAT('0',CAST(w.UNLOADING_POINT_REGIO AS VARCHAR(6))),2)=a.UNLOADINGPOINT_STATE 
AND RIGHT(CONCAT('00',CAST(w.UNLOADING_POINT_COUNTY_CO AS VARCHAR(5))),3)= a.UNLOADINGPOINT_COUNTY_CODE
AND (CAST(a.BILLINGDATE AS DATE) BETWEEN w.VALID_FROM AND w.VALID_TO)
AND a.MATERIALNUMBER=w.MATERIAL_CODE
;
